version: 1.3.0.{build}

pull_requests:
  do_not_increment_build_number: true

environment:
  nuget_key:
    secure: F/R/j3fy1A6ffZTXqECr2zGo8SGjSGHgY0w4hEcQsSCyrybsHtZnNeH7Kug0buLK

# build cache to preserve files/folders between builds
cache:
  - packages -> **\packages.config  # preserve "packages" directory in the root of build folder but will reset it if packages.config is modified
  - '%LocalAppData%\NuGet\Cache'

install:
  - set PATH=C:\Ruby22\bin;%PATH%
  - bundle install
  - bundle exec rake appveyor

build: off

test:
  # assemblies to test - optional
  assemblies:
    - 'C:\projects\moduluschecker\ModulusCheckingTests\bin\Release-netv35\ModulusCheckerTests.dll'
    - 'C:\projects\moduluschecker\ModulusCheckingTests\bin\Release-netv4\ModulusCheckerTests.dll'
    - 'C:\projects\moduluschecker\ModulusCheckingTests\bin\Release-netv45\ModulusCheckerTests.dll'

artifacts:
  - path: C:\projects\moduluschecker\ModulusCheckingTests\bin'
    name: bin_files

  - path: 'C:\projects\moduluschecker\Build\**\*.nuget'
    name: nuget_files
